# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-14 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=10)),
                ('current_time', models.CharField(max_length=8)),
                ('days', models.CharField(max_length=255)),
                ('active', models.PositiveIntegerField()),
                ('finish', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('list', models.TextField()),
                ('active', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=15)),
                ('day', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('start_count', models.PositiveIntegerField()),
                ('end_count', models.PositiveIntegerField()),
                ('weekday', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring', to='planner.Date'),
        ),
        migrations.AddField(
            model_name='activity',
            name='agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='planner.Agenda'),
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='planner.Category'),
        ),
        migrations.AddField(
            model_name='activity',
            name='end_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end', to='planner.Date'),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start', to='planner.Date'),
        ),
    ]
